using System.Text.RegularExpressions;
using FluentValidation; using MediatR; using CustomerService.Application.Abstractions.Notifications; using CustomerService.Application.Abstractions.Persistence; using CustomerService.Domain.Dtos; using CustomerService.Domain.Entities; using CustomerService.Domain.Exceptions;
namespace CustomerService.Application.Registrations;
public sealed record StartRegistrationCommand(string Email,string MobileNumber,RegistrationType Type,string? NationalId,string? LegacyCustomerId):IRequest<StartRegistrationResponse>;
public sealed class StartRegistrationValidator:AbstractValidator<StartRegistrationCommand>{public StartRegistrationValidator(){RuleFor(x=>x.Email).NotEmpty().EmailAddress();RuleFor(x=>x.MobileNumber).NotEmpty().MinimumLength(8);When(x=>x.Type==RegistrationType.ExistingCustomerMigration,()=>RuleFor(x=>x.LegacyCustomerId).NotEmpty());}}
public sealed class StartRegistrationHandler(IRegistrationRepository repo):IRequestHandler<StartRegistrationCommand,StartRegistrationResponse>{public async Task<StartRegistrationResponse> Handle(StartRegistrationCommand r,CancellationToken ct){if(await repo.HasActiveDuplicateAsync(r.Email,r.MobileNumber,r.NationalId,ct))throw new InvalidOperationException("An active or completed registration already exists for the supplied identity.");if(r.Type==RegistrationType.ExistingCustomerMigration&&await repo.GetCustomerByLegacyIdAsync(r.LegacyCustomerId!,ct) is null)throw new NotFoundException("Legacy customer was not found.");var x=RegistrationApplication.Create(r.Email,r.MobileNumber,r.Type,r.NationalId,r.LegacyCustomerId);await repo.AddAsync(x,ct);await repo.AddStepAsync(x.Id,x.CurrentStep,"Completed",ct);await repo.SaveChangesAsync(ct);return new(x.Id,x.Status,x.CurrentStep);}}
public sealed record SendOtpCommand(Guid RegistrationId,OtpChannel Channel):IRequest;
public sealed class SendOtpHandler(IRegistrationRepository repo, IOtpService otp, INotificationDeliveryService deliveryService) : IRequestHandler<SendOtpCommand>
{
    public async Task Handle(SendOtpCommand r, CancellationToken ct)
    {
        var reg = await repo.GetAsync(r.RegistrationId, ct) ?? throw new NotFoundException("Registration not found.");
        var latest = await repo.GetLatestOtpAsync(r.RegistrationId, r.Channel, ct);
        if (latest is not null && DateTime.UtcNow < latest.NextResendAllowedUtc)
            throw new InvalidOperationException($"OTP can be resent after {latest.NextResendAllowedUtc:O}.");
        if (await repo.CountOtpsSinceAsync(r.RegistrationId, r.Channel, DateTime.UtcNow.AddHours(-1), ct) >= 5)
            throw new InvalidOperationException("OTP hourly limit reached.");

        await repo.InvalidateActiveOtpsAsync(r.RegistrationId, r.Channel, ct);
        var code = otp.GenerateCode();
        var hash = otp.Hash(code);
        var challenge = OtpChallenge.Create(r.RegistrationId, r.Channel, hash.Hash, hash.Salt, 10, 5, 60);
        await repo.AddOtpAsync(challenge, ct);

        var notificationChannel = r.Channel == OtpChannel.Email ? NotificationChannel.Email : NotificationChannel.Sms;
        var templateCode = r.Channel == OtpChannel.Email ? "REGISTRATION_EMAIL_OTP" : "REGISTRATION_SMS_OTP";
        var template = await repo.GetTemplateAsync(templateCode, notificationChannel, ct)
            ?? throw new InvalidOperationException("Notification template not found.");

        var delivery = await deliveryService.SendOtpAsync(reg, challenge, template, code, ct);
        await repo.AddStepAsync(reg.Id, r.Channel == OtpChannel.Email ? RegistrationStep.EmailOtpSent : RegistrationStep.SmsOtpSent, delivery.Status.ToString(), ct);
        await repo.SaveChangesAsync(ct);
    }
}
public sealed record VerifyOtpCommand(Guid RegistrationId,OtpChannel Channel,string Otp,string? IpAddress,string? UserAgent):IRequest;
public sealed class VerifyOtpValidator:AbstractValidator<VerifyOtpCommand>{public VerifyOtpValidator()=>RuleFor(x=>x.Otp).Matches("^[0-9]{6}$");}
public sealed class VerifyOtpHandler(IRegistrationRepository repo,IOtpService otp):IRequestHandler<VerifyOtpCommand>{public async Task Handle(VerifyOtpCommand r,CancellationToken ct){var reg=await repo.GetAsync(r.RegistrationId,ct)??throw new NotFoundException("Registration not found.");var ch=await repo.GetLatestOtpAsync(r.RegistrationId,r.Channel,ct)??throw new InvalidOperationException("OTP not found.");var ok=ch.CanVerify&&otp.Verify(r.Otp,ch.CodeHash,ch.Salt);await repo.AddVerificationAttemptAsync(new(){Id=Guid.NewGuid(),OtpChallengeId=ch.Id,WasSuccessful=ok,FailureReason=ok?null:"Invalid, expired, used or locked OTP.",IpAddress=r.IpAddress,UserAgent=r.UserAgent,SubmittedUtc=DateTime.UtcNow},ct);if(!ok){ch.RecordFailedAttempt();await repo.SaveChangesAsync(ct);throw new InvalidOperationException("Invalid or expired OTP.");}ch.MarkVerified();if(r.Channel==OtpChannel.Email)reg.MarkEmailVerified();else reg.MarkSmsVerified();await repo.AddStepAsync(reg.Id,r.Channel==OtpChannel.Email?RegistrationStep.EmailVerified:RegistrationStep.SmsVerified,"Completed",ct);await repo.SaveChangesAsync(ct);}}
public sealed record UpdateRegistrationProfileCommand(Guid Id,string FullName,string? NationalId):IRequest;
public sealed class UpdateRegistrationProfileHandler(IRegistrationRepository repo):IRequestHandler<UpdateRegistrationProfileCommand>{public async Task Handle(UpdateRegistrationProfileCommand r,CancellationToken ct){var x=await repo.GetAsync(r.Id,ct)??throw new NotFoundException("Registration not found.");x.UpdateProfile(r.FullName,r.NationalId);await repo.AddStepAsync(x.Id,RegistrationStep.ProfileCompleted,"Completed",ct);await repo.SaveChangesAsync(ct);}}
public sealed record AcceptTermsCommand(Guid Id,IReadOnlyCollection<Guid> TermIds,string? Ip,string? UserAgent):IRequest;
public sealed class AcceptTermsHandler(IRegistrationRepository repo):IRequestHandler<AcceptTermsCommand>{public async Task Handle(AcceptTermsCommand r,CancellationToken ct){var x=await repo.GetAsync(r.Id,ct)??throw new NotFoundException("Registration not found.");var active=await repo.GetActiveTermsAsync(ct);var required=active.Where(t=>t.IsRequired).Select(t=>t.Id).ToHashSet();if(!required.IsSubsetOf(r.TermIds))throw new InvalidOperationException("All required terms must be accepted.");foreach(var id in r.TermIds.Distinct()){var t=active.SingleOrDefault(a=>a.Id==id)??throw new InvalidOperationException("An invalid or inactive term was supplied.");await repo.AddConsentAsync(new(){Id=Guid.NewGuid(),RegistrationId=x.Id,TermDocumentId=t.Id,TermVersion=t.Version,Accepted=true,AcceptedUtc=DateTime.UtcNow,IpAddress=r.Ip,UserAgent=r.UserAgent},ct);}x.MarkTermsAccepted();await repo.AddStepAsync(x.Id,RegistrationStep.TermsAccepted,"Completed",ct);await repo.SaveChangesAsync(ct);}}
public sealed record SetPinCommand(Guid Id,string Pin,string ConfirmPin):IRequest;
public sealed class SetPinValidator:AbstractValidator<SetPinCommand>{public SetPinValidator(){RuleFor(x=>x.Pin).Matches("^[0-9]{6}$");RuleFor(x=>x.ConfirmPin).Equal(x=>x.Pin);}}
public sealed class SetPinHandler(IRegistrationRepository repo,IPinService pins):IRequestHandler<SetPinCommand>{public async Task Handle(SetPinCommand r,CancellationToken ct){var x=await repo.GetAsync(r.Id,ct)??throw new NotFoundException("Registration not found.");var h=pins.Hash(r.Pin);x.SetPin(h.Hash,h.Salt);await repo.AddStepAsync(x.Id,RegistrationStep.PinConfigured,"Completed",ct);await repo.SaveChangesAsync(ct);}}
public sealed record CompleteRegistrationCommand(Guid Id):IRequest;
public sealed class CompleteRegistrationHandler(IRegistrationRepository repo):IRequestHandler<CompleteRegistrationCommand>{public async Task Handle(CompleteRegistrationCommand r,CancellationToken ct){var x=await repo.GetAsync(r.Id,ct)??throw new NotFoundException("Registration not found.");if(!await repo.HasAcceptedRequiredTermsAsync(x.Id,ct))throw new InvalidOperationException("Required terms are not accepted.");x.Complete();await repo.AddCustomerAsync(new(){Id=Guid.NewGuid(),RegistrationId=x.Id,Email=x.Email,MobileNumber=x.MobileNumber,NationalId=x.NationalId,FullName=x.FullName,LegacyCustomerId=x.LegacyCustomerId,IsMigrated=x.Type==RegistrationType.ExistingCustomerMigration,CreatedUtc=DateTime.UtcNow},ct);await repo.AddStepAsync(x.Id,RegistrationStep.Completed,"Completed",ct);await repo.SaveChangesAsync(ct);}}
public sealed record CancelRegistrationCommand(Guid Id,string Reason):IRequest;public sealed class CancelRegistrationHandler(IRegistrationRepository repo):IRequestHandler<CancelRegistrationCommand>{public async Task Handle(CancelRegistrationCommand r,CancellationToken ct){var x=await repo.GetAsync(r.Id,ct)??throw new NotFoundException("Registration not found.");x.Cancel(r.Reason);await repo.SaveChangesAsync(ct);}}
public sealed record GetRegistrationQuery(Guid Id):IRequest<RegistrationDto>;public sealed class GetRegistrationHandler(IRegistrationRepository repo):IRequestHandler<GetRegistrationQuery,RegistrationDto>{public async Task<RegistrationDto> Handle(GetRegistrationQuery r,CancellationToken ct){var x=await repo.GetAsync(r.Id,ct)??throw new NotFoundException("Registration not found.");return new(x.Id,x.Type,x.Status,x.CurrentStep,x.Email,x.MobileNumber,x.NationalId,x.FullName,x.LegacyCustomerId,x.EmailVerified,x.SmsVerified,x.PinSetUtc is not null,x.ExpiresUtc,x.CreatedUtc,x.UpdatedUtc);}}
public sealed record GetDeliveriesQuery(Guid Id):IRequest<IReadOnlyList<NotificationDeliveryDto>>;public sealed class GetDeliveriesHandler(IRegistrationRepository repo):IRequestHandler<GetDeliveriesQuery,IReadOnlyList<NotificationDeliveryDto>>{public async Task<IReadOnlyList<NotificationDeliveryDto>> Handle(GetDeliveriesQuery r,CancellationToken ct)=>(await repo.GetDeliveriesAsync(r.Id,ct)).Select(x=>new NotificationDeliveryDto(x.Id,x.Channel,x.Destination,x.TemplateCode,x.Status,x.AttemptCount,x.ProviderMessageId,x.FailureReason,x.CreatedUtc,x.SentUtc)).ToList();}
