IF DB_ID(N'CustomerServiceDb') IS NULL CREATE DATABASE CustomerServiceDb; GO
USE CustomerServiceDb; GO
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name='reg') EXEC('CREATE SCHEMA reg');
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name='notify') EXEC('CREATE SCHEMA notify');
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name='crm') EXEC('CREATE SCHEMA crm'); GO
DROP TABLE IF EXISTS integration.OutboxMessages; GO
IF OBJECT_ID('reg.RegistrationApplications') IS NULL
CREATE TABLE reg.RegistrationApplications(Id uniqueidentifier NOT NULL PRIMARY KEY,Type int NOT NULL,Status int NOT NULL,CurrentStep int NOT NULL,Email nvarchar(320) NOT NULL,NormalizedEmail nvarchar(320) NOT NULL,MobileNumber nvarchar(30) NOT NULL,NormalizedMobileNumber nvarchar(30) NOT NULL,NationalId nvarchar(100) NULL,FullName nvarchar(200) NULL,LegacyCustomerId nvarchar(100) NULL,EmailVerified bit NOT NULL DEFAULT 0,SmsVerified bit NOT NULL DEFAULT 0,PinHash nvarchar(256) NULL,PinSalt nvarchar(256) NULL,PinSetUtc datetime2 NULL,FailedPinAttempts int NOT NULL DEFAULT 0,PinLockedUntilUtc datetime2 NULL,ExpiresUtc datetime2 NOT NULL,CancelledUtc datetime2 NULL,CancellationReason nvarchar(500) NULL,CreatedUtc datetime2 NOT NULL,UpdatedUtc datetime2 NOT NULL,RowVersion rowversion NOT NULL); GO
CREATE INDEX IX_Reg_Email ON reg.RegistrationApplications(NormalizedEmail); CREATE INDEX IX_Reg_Mobile ON reg.RegistrationApplications(NormalizedMobileNumber); GO
IF OBJECT_ID('reg.OtpChallenges') IS NULL CREATE TABLE reg.OtpChallenges(Id uniqueidentifier PRIMARY KEY,RegistrationId uniqueidentifier NOT NULL,Channel int NOT NULL,CodeHash nvarchar(128) NOT NULL,Salt nvarchar(128) NOT NULL,ExpiresUtc datetime2 NOT NULL,AttemptCount int NOT NULL DEFAULT 0,MaxAttempts int NOT NULL,VerifiedUtc datetime2 NULL,InvalidatedUtc datetime2 NULL,CreatedUtc datetime2 NOT NULL,NextResendAllowedUtc datetime2 NOT NULL,CONSTRAINT FK_Otp_Reg FOREIGN KEY(RegistrationId) REFERENCES reg.RegistrationApplications(Id)); GO
IF OBJECT_ID('reg.OtpVerificationAttempts') IS NULL CREATE TABLE reg.OtpVerificationAttempts(Id uniqueidentifier PRIMARY KEY,OtpChallengeId uniqueidentifier NOT NULL,WasSuccessful bit NOT NULL,FailureReason nvarchar(500) NULL,IpAddress nvarchar(64) NULL,UserAgent nvarchar(500) NULL,SubmittedUtc datetime2 NOT NULL,CONSTRAINT FK_OtpAttempt_Otp FOREIGN KEY(OtpChallengeId) REFERENCES reg.OtpChallenges(Id)); GO
IF OBJECT_ID('reg.TermDocuments') IS NULL CREATE TABLE reg.TermDocuments(Id uniqueidentifier PRIMARY KEY,Code nvarchar(100) NOT NULL,Title nvarchar(300) NOT NULL,Content nvarchar(max) NOT NULL,Version nvarchar(50) NOT NULL,IsRequired bit NOT NULL,IsActive bit NOT NULL,EffectiveFromUtc datetime2 NOT NULL,EffectiveToUtc datetime2 NULL,CreatedUtc datetime2 NOT NULL,UpdatedUtc datetime2 NOT NULL,CONSTRAINT UQ_Term_Code_Version UNIQUE(Code,Version)); GO
IF OBJECT_ID('reg.RegistrationConsents') IS NULL CREATE TABLE reg.RegistrationConsents(Id uniqueidentifier PRIMARY KEY,RegistrationId uniqueidentifier NOT NULL,TermDocumentId uniqueidentifier NOT NULL,TermVersion nvarchar(50) NOT NULL,Accepted bit NOT NULL,AcceptedUtc datetime2 NOT NULL,IpAddress nvarchar(64) NULL,UserAgent nvarchar(500) NULL,CONSTRAINT FK_Consent_Reg FOREIGN KEY(RegistrationId) REFERENCES reg.RegistrationApplications(Id),CONSTRAINT FK_Consent_Term FOREIGN KEY(TermDocumentId) REFERENCES reg.TermDocuments(Id),CONSTRAINT UQ_Consent UNIQUE(RegistrationId,TermDocumentId,TermVersion)); GO
IF OBJECT_ID('reg.RegistrationStepHistory') IS NULL CREATE TABLE reg.RegistrationStepHistory(Id uniqueidentifier PRIMARY KEY,RegistrationId uniqueidentifier NOT NULL,Step int NOT NULL,Status nvarchar(50) NOT NULL,OccurredUtc datetime2 NOT NULL,CONSTRAINT FK_Step_Reg FOREIGN KEY(RegistrationId) REFERENCES reg.RegistrationApplications(Id)); GO
IF OBJECT_ID('notify.NotificationTemplates') IS NULL CREATE TABLE notify.NotificationTemplates(Id uniqueidentifier PRIMARY KEY,Code nvarchar(100) NOT NULL,Name nvarchar(200) NOT NULL,Channel int NOT NULL,SubjectTemplate nvarchar(500) NULL,BodyTemplate nvarchar(max) NOT NULL,IsHtml bit NOT NULL,IsActive bit NOT NULL,Version int NOT NULL,CreatedUtc datetime2 NOT NULL,UpdatedUtc datetime2 NOT NULL); GO
IF OBJECT_ID('notify.NotificationDeliveries') IS NULL CREATE TABLE notify.NotificationDeliveries(Id uniqueidentifier PRIMARY KEY,RegistrationId uniqueidentifier NOT NULL,OtpChallengeId uniqueidentifier NULL,Channel int NOT NULL,Destination nvarchar(320) NOT NULL,TemplateCode nvarchar(100) NOT NULL,Status int NOT NULL,AttemptCount int NOT NULL,ProviderMessageId nvarchar(200) NULL,FailureReason nvarchar(2000) NULL,CreatedUtc datetime2 NOT NULL,SentUtc datetime2 NULL,UpdatedUtc datetime2 NOT NULL,CONSTRAINT FK_Delivery_Reg FOREIGN KEY(RegistrationId) REFERENCES reg.RegistrationApplications(Id),CONSTRAINT FK_Delivery_Otp FOREIGN KEY(OtpChallengeId) REFERENCES reg.OtpChallenges(Id)); GO
IF OBJECT_ID('crm.CustomerAccounts') IS NULL CREATE TABLE crm.CustomerAccounts(Id uniqueidentifier PRIMARY KEY,RegistrationId uniqueidentifier NOT NULL UNIQUE,Email nvarchar(320) NOT NULL,MobileNumber nvarchar(30) NOT NULL,NationalId nvarchar(100) NULL,FullName nvarchar(200) NULL,LegacyCustomerId nvarchar(100) NULL,IsMigrated bit NOT NULL,CreatedUtc datetime2 NOT NULL,CONSTRAINT FK_Customer_Reg FOREIGN KEY(RegistrationId) REFERENCES reg.RegistrationApplications(Id)); GO
DECLARE @now datetime2=SYSUTCDATETIME();
IF NOT EXISTS(SELECT 1 FROM reg.TermDocuments WHERE Code='TERMS_OF_USE' AND Version='1.0') INSERT reg.TermDocuments VALUES(NEWID(),'TERMS_OF_USE','Terms of Use','Replace this seed text with the approved Terms of Use content.','1.0',1,1,@now,NULL,@now,@now);
IF NOT EXISTS(SELECT 1 FROM reg.TermDocuments WHERE Code='PRIVACY_POLICY' AND Version='1.0') INSERT reg.TermDocuments VALUES(NEWID(),'PRIVACY_POLICY','Privacy Policy','Replace this seed text with the approved Privacy Policy content.','1.0',1,1,@now,NULL,@now,@now);
IF NOT EXISTS(SELECT 1 FROM notify.NotificationTemplates WHERE Code='REGISTRATION_EMAIL_OTP' AND Channel=1) INSERT notify.NotificationTemplates VALUES(NEWID(),'REGISTRATION_EMAIL_OTP','Registration email OTP',1,'Your verification code','<p>Hello {{FullName}},</p><p>Your code is <strong>{{OtpCode}}</strong>.</p><p>It expires in {{ExpiryMinutes}} minutes.</p>',1,1,1,@now,@now);
IF NOT EXISTS(SELECT 1 FROM notify.NotificationTemplates WHERE Code='REGISTRATION_SMS_OTP' AND Channel=2) INSERT notify.NotificationTemplates VALUES(NEWID(),'REGISTRATION_SMS_OTP','Registration SMS OTP',2,NULL,'Your verification code is {{OtpCode}}. It expires in {{ExpiryMinutes}} minutes.',0,1,1,@now,@now); GO
