using CustomerService.Domain.Entities;
namespace CustomerService.Domain.Dtos;
public sealed record StartRegistrationRequest(string Email,string MobileNumber,RegistrationType Type,string? NationalId,string? LegacyCustomerId);
public sealed record StartRegistrationResponse(Guid RegistrationId,RegistrationStatus Status,RegistrationStep CurrentStep);
public sealed record UpdateProfileRequest(string FullName,string? NationalId);
public sealed record VerifyOtpRequest(string Otp);
public sealed record SetPinRequest(string Pin,string ConfirmPin);
public sealed record CancelRegistrationRequest(string Reason);
public sealed record AcceptTermsRequest(IReadOnlyCollection<Guid> TermIds);
public sealed record MigrationLookupRequest(string LegacyCustomerId,string? NationalId,string? MobileNumber);
public sealed record RegistrationDto(Guid Id,RegistrationType Type,RegistrationStatus Status,RegistrationStep CurrentStep,string Email,string MobileNumber,string? NationalId,string? FullName,string? LegacyCustomerId,bool EmailVerified,bool SmsVerified,bool PinConfigured,DateTime ExpiresUtc,DateTime CreatedUtc,DateTime UpdatedUtc);
public sealed record TermDocumentDto(Guid Id,string Code,string Title,string Content,string Version,bool IsRequired,DateTime EffectiveFromUtc);
public sealed record NotificationDeliveryDto(Guid Id,NotificationChannel Channel,string Destination,string TemplateCode,DeliveryStatus Status,int AttemptCount,string? ProviderMessageId,string? FailureReason,DateTime CreatedUtc,DateTime? SentUtc);
